-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS multidisciplinario.favorite
(
    "idFavorite" serial NOT NULL,
    "idUser" integer NOT NULL,
    "idPlace" character varying(24) COLLATE pg_catalog."default",
    CONSTRAINT favorite_pkey PRIMARY KEY ("idFavorite")
);

CREATE TABLE IF NOT EXISTS multidisciplinario.outing
(
    "idOuting" serial NOT NULL,
    "idUser" integer NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT outing_pkey PRIMARY KEY ("idOuting")
);

CREATE TABLE IF NOT EXISTS multidisciplinario.roles
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS multidisciplinario.tags
(
    id serial NOT NULL,
    "tagsEvent" character varying(50) COLLATE pg_catalog."default",
    "tagsPlace" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS multidisciplinario.users
(
    id serial NOT NULL,
    "id_Rol" integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    premium_expiration timestamp without time zone,
    "eventReminder" character varying[] COLLATE pg_catalog."default",
    "ContentReminder" character varying[] COLLATE pg_catalog."default",
    "nameReminder" character varying[] COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS multidisciplinario.favorite
    ADD CONSTRAINT "favorite_idUser_fkey" FOREIGN KEY ("idUser")
    REFERENCES multidisciplinario.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS multidisciplinario.outing
    ADD CONSTRAINT "outing_idUser_fkey" FOREIGN KEY ("idUser")
    REFERENCES multidisciplinario.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS multidisciplinario.users
    ADD CONSTRAINT "users_id_Rol_fkey" FOREIGN KEY ("id_Rol")
    REFERENCES multidisciplinario.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;